# Generated by Django 5.0 on 2026-01-08 18:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0004_curatedobservation_sex"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="curatedobservation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="curatedobservation",
            name="dataset_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="curatedobservation",
            name="occurrence_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Darwin Core occurrenceID - unique across OBIS/GBIF",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="curatedobservation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="curatedobservation",
            name="observation_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="curatedobservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("OBIS", "OBIS Direct"),
                    ("GBIF", "GBIF Direct"),
                    ("BOTH", "Both APIs"),
                ],
                db_index=True,
                default="OBIS",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="curatedobservation",
            index=models.Index(
                fields=["occurrence_id"], name="species_cur_occurre_f5e035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curatedobservation",
            index=models.Index(
                fields=["source"], name="species_cur_source_ac219f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curatedobservation",
            index=models.Index(
                fields=["-observation_date"],
                name="species_cur_observa_771594_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="curatedobservation",
            index=models.Index(
                fields=["species_name"], name="species_cur_species_ad83bb_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="curatedobservation",
            name="obis_id",
        ),
        migrations.RemoveField(
            model_name="curatedobservation",
            name="raw_data",
        ),
        migrations.RemoveField(
            model_name="curatedobservation",
            name="user",
        ),
    ]
