# Generated by Django 5.0 on 2026-01-13 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0005_alter_curatedobservation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedobservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="curatedobservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
