# Generated by Django 5.0 on 2026-01-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedEmailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.CharField(
                        help_text="Email domain (e.g., marine.university.edu)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "ror_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "auto_approve_to_community",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Automatically verify users to Community tier"
                        ),
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Trusted Email Domain",
                "verbose_name_plural": "Trusted Email Domains",
                "ordering": ["organization_name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Brief professional bio (optional)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="institution_name",
            field=models.CharField(
                blank=True,
                help_text="Name of research institution or organization",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(
                blank=True,
                help_text="ORCID identifier (format: 0000-0000-0000-0000)",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="research_focus",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of research focus areas",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ror_id",
            field=models.CharField(
                blank=True,
                help_text="Research Organization Registry ID",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about verification process"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="researchers_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="years_experience",
            field=models.IntegerField(
                blank=True, help_text="Years of research experience", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("hobbyist", "Hobbyist"),
                    (
                        "researcher_pending",
                        "Researcher - Pending Verification",
                    ),
                    (
                        "researcher_community",
                        "Researcher - Community Verified",
                    ),
                    (
                        "researcher_institutional",
                        "Researcher - Institutionally Verified",
                    ),
                ],
                default="hobbyist",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role"], name="users_user_role_36d76d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["orcid"], name="users_user_orcid_1fd3f9_idx"
            ),
        ),
    ]
